import React from 'react';
import { ArrowLeft } from 'lucide-react';

export function TermsConditions({ onBack }: { onBack: () => void }) {
  return (
    <div className="flex flex-col h-full bg-black text-white overflow-hidden">
      {/* Header */}
      <header className="flex items-center p-4 border-b border-white/10 bg-zinc-900/50 backdrop-blur-md sticky top-0 z-10">
        <button 
          onClick={onBack}
          className="p-2 -ml-2 mr-2 rounded-full hover:bg-white/10 transition-colors"
        >
          <ArrowLeft className="w-6 h-6" />
        </button>
        <h1 className="text-xl font-bold">Terms & Conditions</h1>
      </header>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-6 space-y-6 pb-24">
        <div className="prose prose-invert max-w-none">
          <p className="text-zinc-400 text-sm mb-6">Last Updated: March 2026</p>

          <section className="mb-8">
            <h2 className="text-lg font-bold text-purple-400 mb-3">1. Acceptance of Terms</h2>
            <p className="text-zinc-300 leading-relaxed">
              By downloading, accessing, or using SavageAI Bangla, you agree to these Terms and Conditions. If you do not agree, please do not use the app.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-lg font-bold text-purple-400 mb-3">2. Use of Service</h2>
            <ul className="list-disc pl-5 text-zinc-300 space-y-2">
              <li>The app is intended for entertainment purposes only.</li>
              <li>AI-generated content (roasts) may not always be accurate, appropriate, or reliable.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-lg font-bold text-purple-400 mb-3">3. Content Rules</h2>
            <p className="text-zinc-300 leading-relaxed mb-2">Users must NOT:</p>
            <ul className="list-disc pl-5 text-zinc-300 space-y-2">
              <li>Use the app for harassment, bullying, or targeted abuse.</li>
              <li>Promote hate speech, violence, or illegal activities.</li>
              <li>Misuse the generated content to harm others.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-lg font-bold text-purple-400 mb-3">4. AI Limitations</h2>
            <p className="text-zinc-300 leading-relaxed">
              Roasts are automatically generated by Artificial Intelligence. They are not intended to harm, insult, or defame real individuals. The AI's responses do not reflect the opinions of the developers.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-lg font-bold text-purple-400 mb-3">5. Ads & Monetization</h2>
            <ul className="list-disc pl-5 text-zinc-300 space-y-2">
              <li>The app shows advertisements via Google AdMob to support development.</li>
              <li>Users may choose to watch rewarded video ads to unlock additional features or daily limits.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-lg font-bold text-purple-400 mb-3">6. Limitation of Liability</h2>
            <p className="text-zinc-300 leading-relaxed font-medium">
              The app is not responsible for any emotional impact, offense, or damages caused by the AI-generated content. Use the app at your own risk.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-lg font-bold text-purple-400 mb-3">7. Termination</h2>
            <p className="text-zinc-300 leading-relaxed">
              We reserve the right to block or terminate access for users who are found to be abusive, violating these terms, or misusing the service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-lg font-bold text-purple-400 mb-3">8. Changes</h2>
            <p className="text-zinc-300 leading-relaxed">
              These Terms may change anytime without prior notice. Continued use of the app constitutes acceptance of the new terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-lg font-bold text-purple-400 mb-3">9. Contact</h2>
            <p className="text-zinc-300 leading-relaxed">
              If you have any questions about these Terms, please contact us at:<br/>
              <a href="mailto:support@savageai.app" className="text-purple-400 hover:underline">support@savageai.app</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
